### ISSUE TITLE
running acrobat and hiv experiments got errors

### ISSUE THREAD

**Issue by Erichliu00** [dtak/hip-mdp-public#2]
Running codes by setting  `domain = 'hiv'` got error: 

```
Traceback (most recent call last):
  File "hiv_baseline.py", line 58, in <module>
    sys_param_set, mean_episode_errors, std_episode_errors) = batch_generator_hipmdp.run_experiment()
  File "/home/hao/Dropbox/CODE/bnn/HiPMDP.py", line 622, in run_experiment
    self.run_instance()
  File "/home/hao/Dropbox/CODE/bnn/HiPMDP.py", line 478, in run_instance
    self.__get_instance_param_set()
  File "/home/hao/Dropbox/ICML18/bnn/HiPMDP.py", line 213, in __get_instance_param_set
    self.instance_param_set = self.preset_hidden_params[instance_idx]
IndexError: list index out of range
```

On acrobot experiments, [line2](https://github.com/dtak/hip-mdp-public/blob/master/acrobot_simulator/acrobot.py#L2) import `check_random_state ` from acro_utlis.py, however, there is no `check_random_state` there.

**Comment by twkillian** [comment]
What other settings did you have when trying to run the HIV domain? It's hard to diagnose without seeing what you put into creating `batch_generator_hipmdp`...

As far as the acrobot error. check_random_state was a holdover method from a previous iteration that we did away with as we improved our code. It must have been carried over as we uploaded our updated files to this public repo. This should be resolved by just removing that import. I've also updated our repo with the offending method removed. Thanks for pointing that out.

**Comment by Erichliu00** [comment]
Thanks for quick response! What I did before running HIV was changing hyperparameters as said in your paper, and change the domain to `HIV`.  I would be very appreciated if you could also upload something like a script or ipynb to run that HIV.

**Comment by Erichliu00** [comment]
Any suggestions would be very appreciated! BTW, did you try increasing the batch size of Q-network?

**Comment by twkillian** [comment]
I'll put up an example in the next couple of days, I don't want to rush through it without adequately testing. Sorry to keep you waiting.

We did play with batch size for the Q-network in a limited fashion early on in our experimentation. There wasn't a huge effect that motivated the switch then as we had bigger issues that we needed to iron out before submitting and publishing the paper. We also didn't really consider decreasing the buffer size for a particular task instance. We certainly could have but wanted to be sure that they were big enough to contain all the data observed over the course of both true and fictional (BNN-approximated) episodes during an instance.

**Comment by twkillian** [comment]
@Erichliu00 I'm pretty sure that I've isolated your problem... We didn't provide any guidance in how to set the ``preset_hidden_params`` for domains other than ``grid``. What you need to do is load the ``preset_parameters/[domain]_preset_hidden_params`` and then choose how big of a batch you want to train your initial BNN from. With the ``HIV`` domain we have 6 separate instances saved. In our paper, we used the first five to train the BNN and then tested on the sixth. 

With ``Acrobot``, we have 100 separate instances saved. In the paper, we again used 5 to train the initial batch and trained on the 6th. 

In any case, I'll update ``toy_example.ipynb`` to provide some guidance on how to do this for the domains beyond ``Grid``

@sdaulton You may want to confirm this.

**Comment by haoliuhl** [comment]
Thanks a lot, will try!

**Comment by twkillian** [comment]
:+1:
